version: "2"
services:
  mysql:
    container_name: mysql_container
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=mysql_root_pswd
    network_mode: "host"
    volumes:
#     - /home/dockeruser/vl_client_db:/var/lib/mysql TODO actual path to dir
      - /home/dkarpov/projects/self/rocket/db:/var/lib/mysql
    ports:
      - "3306:3306"
  app:
    container_name: app_container
    image: rocket_app
    depends_on:
      - mysql
    network_mode: "host"
    volumes:
#      - /usr/bin/firefox:/usr/bin/firefox
#      - /usr/lib/firefox:/usr/lib/firefox
#      - /usr/bin/geckodriver:/usr/bin/geckodriver
      - /tmp:/tmp
    ports:
      - "0.0.0.0:8000:8000"
