version: "2"
services:
  mysql:
    container_name: mysql_container
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=mysql_root_pswd
    network_mode: "host"
    volumes:

      - /home/dkarpov/projects/self/rocket/db:/var/lib/mysql
      - /home/dkarpov/projects/self/rocket/parsing_results/category:/home/dockeruser/parsing_results/category
      # - /home/dockeruser/vl_client_db:/var/lib/mysql TODO actual path to dir
#    ports:
#      - "3306:3306"
  app:
    container_name: app_container
    image: rocket_app
    depends_on:
      - mysql
    network_mode: "host"
    volumes:
      - /tmp:/tmp
    ports:
      - "0.0.0.0:8000:8000"
