# Generated by Django 3.1.3 on 2020-12-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0002_producturl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producturl',
            name='marketplace',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.DeleteModel(
            name='CategoryUrl',
        ),
        migrations.DeleteModel(
            name='ProductUrl',
        ),
    ]
