# Generated by Django 3.1.3 on 2020-12-28 22:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0004_auto_20201227_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='RegionCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('marketplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser_app.marketplace')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser_app.region')),
            ],
        ),
        migrations.CreateModel(
            name='ProductParsing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'created'), ('progress', 'progress'), ('done', 'done')], max_length=100)),
                ('result_file', models.CharField(max_length=1000, null=True)),
                ('comment', models.TextField(max_length=5000, null=True)),
                ('error', models.TextField(max_length=5000, null=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(null=True)),
                ('duration', models.IntegerField(null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser_app.product')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser_app.region')),
            ],
        ),
    ]
