# Generated by Django 3.1.3 on 2021-01-05 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0005_productparsing_region_regioncode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productparsing',
            name='comment',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='productparsing',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productparsing',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productparsing',
            name='error',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='productparsing',
            name='result_file',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='productparsing',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('scheduled', 'scheduled'), ('progress', 'progress'), ('done', 'done')], default='created', max_length=100),
        ),
    ]
