# Generated by Django 3.1.3 on 2021-01-12 22:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0006_auto_20210106_0121'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryParsing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'created'), ('scheduled', 'scheduled'), ('progress', 'progress'), ('done', 'done')], default='created', max_length=100)),
                ('result_file', models.CharField(blank=True, max_length=1000, null=True)),
                ('comment', models.TextField(blank=True, max_length=5000, null=True)),
                ('error', models.TextField(blank=True, max_length=5000, null=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser_app.product')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser_app.region')),
            ],
        ),
    ]
