# Generated by Django 3.1.3 on 2021-01-12 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0007_categoryparsing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryparsing',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser_app.category'),
        ),
    ]
