# Generated by Django 3.1.3 on 2021-01-31 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0008_auto_20210113_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryparsing',
            name='duration',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productparsing',
            name='duration',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
